Dime\TimetrackerBundle\Entity\Service:
    service1:
        name: consulting
        alias: consulting
        vat: 0.08
        chargeable: true
        rates: 2x @rateHour*
        user: @user1
    serviceHour{1..3}:
        name: <word()>
        alias: <slug()>
        vat: <randomElement(array (0.025, 0.08))>
        chargeable: true
        rates: 2x @rateHour*
    serviceDay{1..3}:
        name: <word()>
        alias: <slug()>
        vat: <randomElement(array (0.025, 0.08))>
        chargeable: true
        rates: 2x @rateDay*
    serviceNone{1..3}:
        name: <word()>
        alias: <slug()>
        vat: <randomElement(array (0.025, 0.08))>
        chargeable: true
        rates: 2x @rateNone*
    servicePauschal{1..3}:
        name: <word()>
        alias: <slug()>
        vat: <randomElement(array (0.025, 0.08))>
        chargeable: true
        rates: 2x @ratePauschal*