services:
        dime.discount.form.type:
            class: Dime\InvoiceBundle\Form\Type\InvoiceDiscountFormType
            tags: [{ name: "form.type", alias: "dime_invoicebundle_discountformtype" }]