invoices:
    type:     rest
    resource: Dime\InvoiceBundle\Controller\InvoiceController
    prefix:   /v1
    name_prefix:  api_1_
    defaults: { _format: json }

invoiceDiscounts:
    type:     rest
    resource: Dime\InvoiceBundle\Controller\DiscountController
    prefix:   /v1
    name_prefix:  api_1_
    defaults: { _format: json }