parameters:
    generic_handler: "Dime\TimetrackerBundle\Handler\GenericHandler"

services:
    dime.user.handler:
        class: "Dime\TimetrackerBundle\Handler\UserHandler"
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\User", "@form.factory", "@security.context", "@fos_user.user_manager", "us", "dime_timetrackerbundle_userformtype" ]
        
    dime.timeslice.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Timeslice", "@form.factory", "@security.context", "ti", "dime_timetrackerbundle_timesliceformtype"]
        
    dime.tag.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Tag", "@form.factory", "@security.context", "t", "dime_timetrackerbundle_tagformtype"]
        
    dime.setting.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Setting", "@form.factory", "@security.context", "se", "dime_timetrackerbundle_settingformtype"]
        
    dime.service.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Service", "@form.factory", "@security.context", "s", "dime_timetrackerbundle_serviceformtype"]
        
    dime.project.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\\Project", "@form.factory", "@security.context", "p", "dime_timetrackerbundle_projectformtype"]
        
    dime.customer.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Customer", "@form.factory", "@security.context", "c", "dime_timetrackerbundle_customerformtype"]
        
    dime.activity.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Activity", "@form.factory", "@security.context", "a", "dime_timetrackerbundle_activityformtype"]
        
    dime.rategroup.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\RateGroup", "@form.factory", "@security.context", "rg", "dime_timetrackerbundle_rategroupformtype"]
        
    dime.rate.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Rate", "@form.factory", "@security.context", "r", "dime_timetrackerbundle_rateformtype"]
        
    dime.standarddiscount.handler:
         class: %generic_handler%
         arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\StandardDiscount", "@form.factory", "@security.context", "sd", "dime_timetrackerbundle_standarddiscountformtype"]

