services:
    dime.user.handler:
        class: "Dime\TimetrackerBundle\Handler\UserHandler"
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\User", "@form.factory", "@security.context", "@fos_user.user_manager" ]
        
    dime.timeslice.handler:
        class: "Dime\TimetrackerBundle\Handler\TimesliceHandler"
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Timeslice", "@form.factory", "@security.context"]
        
    dime.tag.handler:
        class: "Dime\TimetrackerBundle\Handler\TagHandler"
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Tag", "@form.factory", "@security.context"]
        
    dime.setting.handler:
        class: "Dime\TimetrackerBundle\Handler\SettingHandler"
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Setting", "@form.factory", "@security.context"]
        
    dime.service.handler:
        class: "Dime\TimetrackerBundle\Handler\ServiceHandler"
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Service", "@form.factory", "@security.context"]
        
    dime.project.handler:
        class: "Dime\TimetrackerBundle\Handler\ProjectHandler"
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\\Project", "@form.factory", "@security.context"]
        
    dime.customer.handler:
        class: "Dime\TimetrackerBundle\Handler\CustomerHandler"
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Customer", "@form.factory", "@security.context"]
        
    dime.activity.handler:
        class: "Dime\TimetrackerBundle\Handler\ActivityHandler"
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Activity", "@form.factory", "@security.context"]
        
    dime.rategroup.handler:
        class: "Dime\TimetrackerBundle\Handler\RateGroupHandler"
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\RateGroup", "@form.factory", "@security.context"]
        
    dime.rate.handler:
        class: "Dime\TimetrackerBundle\Handler\RateHandler"
        arguments: [ "@doctrine.orm.entity_manager", "Dime\TimetrackerBundle\Entity\Rate", "@form.factory", "@security.context"]
        
        