parameters:
    generic_handler: "Dime\EmployeeBundle\Handler\GenericHandler"

services:
    dime.employee.handler:
        class: "Dime\EmployeeBundle\Handler\UserHandler"
        arguments: [ "@doctrine.orm.entity_manager", "Dime\EmployeeBundle\Entity\Employee", "@service_container", "em", "dime_EmployeeBundle_employeeformtype" ]
        
