parameters:
    generic_handler: "Dime\EmployeeBundle\Handler\GenericHandler"

services:
    dime.employee.handler:
        class: "Dime\TimetrackerBundle\Handler\UserHandler"
        arguments: [ "@doctrine.orm.entity_manager", "Dime\EmployeeBundle\Entity\Employee", "@service_container", "@fos_user.user_manager", "em", "dime_employeeBundle_employeeformtype" ]

    dime.period.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", "Dime\EmployeeBundle\Entity\Period",  "@service_container", "p", "dime_employeebundle_periodformtype"]