version: '2'
services:
  dime:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dime
    hostname: dime
    ports:
      - "3000:8080"
    links:
      - mariadb:mysql
    volumes:
      - dime-sync:/var/www/html:nocopy
      - pub-cache:/tmp/dime-pub-cache
    environment:
      - VIRTUAL_HOST=localhost
      - PUB_CACHE=/var/www/html/src/Dime/FrontendBundle/Resources/public/pubcache
      - PHP_MEMLIMIT="2048M"
      - CACHE_ROOT="/tmp/app"

  mariadb:
    image: mysql:5.6.33
    container_name: mariadb
    hostname: mariadb
    ports:
      - "3010:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USER=dime
      - MYSQL_PASSWORD=dime

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    ports:
     - 8080:80

volumes:
  dime-sync:
    external: true
  pub-cache:
    external: false
