version: '2'
services:
  dime:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dime
    hostname: dime
    ports:
      - "3000:8080"
    links:
      - mysql:mysql
    volumes:
      - .:/var/www/html:cached
    environment:
      - VIRTUAL_HOST=localhost
      - PHP_MEMLIMIT="2048M"
      - CACHE_ROOT="/tmp/app"

  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    ports:
      - "3010:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USER=dime
      - MYSQL_PASSWORD=dime

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    ports:
     - 8080:80
