<?php

namespace Swo\CustomerBundle\Entity;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends AbstractCustomerRepository
{
}
