parameters:

services:
    dime.print.pdf:
        class: 'Dime\PrintingBundle\Service\PrintService'
        arguments: [ '@templating', '@ps_pdf.facade_builder', '@ps_pdf.cache' ]

    charbox.twig_extension:
        class: Dime\PrintingBundle\Extensions\CharBoxExtension
        public: false
        tags:
            - { name: twig.extension }