<?php

namespace Dime\TimetrackerBundle\Entity;

use Dime\TimetrackerBundle\Entity\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     *
     * @param string            $text
     * @param QueryBuilder      $qb
     *
     * @return UserRepository
     */
    public function search($text, QueryBuilder $qb = null)
    {
        return $this;
    }

    /**
     *
     * @param                   $date
     * @param QueryBuilder      $qb
     *
     * @return UserRepository
     */
    public function scopeByDate($date, QueryBuilder $qb = null)
    {
        return $this;
    }

	/**
	 *
	 * @param unknown $limit
	 * @param unknown $offset
	 *
	 * @return array
	 */
    public function findSafeBy($limit, $offset)
    {
        return $this->getEntityManager()
        ->createQuery(
            'SELECT u.id, u.username, u.firstname, u.lastname, u.createdAt, u.updatedAt, u.email, u.enabled FROM DimeTimetrackerBundle:User u'
        )
        ->setMaxResults($limit)
        ->setFirstResult($offset)
        ->getResult();
    }

}
