imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ DimeTimetrackerFrontendBundle ]
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

# JMSSecurityExtra
jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

# JMSSerializerBundle (required by FosRestBundle)
jms_serializer:
    handlers:
        object_based: false
        datetime:
            format: Y-m-dTH:i:s
            default_timezone: UTC
        array_collection: true
        form_error: true
        constraint_violation: true

    property_naming:
        separator:  _
        lower_case: true

    metadata:
        cache: file
        debug: %kernel.debug%
        file_cache:
            dir: %kernel.cache_dir%/serializer

        # Using auto-detection, the mapping files for each bundle will be
        # expected in the Resources/config/serializer directory.
        #
        # Example:
        # class: My\FooBundle\Entity\User
        # expected path: @MyFooBundle/Resources/config/serializer/Entity.User.(yml|xml|php)
        auto_detection: true

        # if you don't want to use auto-detection, you can also define the
        # namespace prefix and the corresponding directory explicitly
        # directories:
        #     any-name:
        #         namespace_prefix: My\FooBundle
        #         path: @MyFooBundle/Resources/config/serializer
        #     another-name:
        #         namespace_prefix: My\BarBundle
        #         path: @MyBarBundle/Resources/config/serializer

fos_rest:
    view:
        formats:
            json: true
            xml: false
        templating_formats:
            html: true
        force_redirects:
            html: false
        failed_validation: HTTP_BAD_REQUEST
        #default_engine: twig
