imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@DimeTimetrackerBundle/Resources/config/config.yml" }
    - { resource: "@DimeFrontendBundle/Resources/config/config.yml" }
    - { resource: "@DimeInvoiceBundle/Resources/config/services.yml"}

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'TbbcMoneyBundle:Form:fields.html.twig'
    globals:
        dime_release_mode: "%dime_release_mode%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        path:     "%database_path%"
        types:
          phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
stof_doctrine_extensions:
    default_locale: en_US

services:
  gedmo.listener.softdeleteable:
    class: Gedmo\SoftDeleteable\SoftDeleteableListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

nelmio_api_doc: ~

tbbc_money:
    currencies: ["CHF"]
    reference_currency: "CHF"
    decimals: 2

dime_invoice:
    sender:
        name: "%sender_name%"
        plz: "%sender_plz%"
        city: "%sender_city%"
        street: "%sender_street%"
        streetnumber: "%sender_streetnumber%"
        phone: "%sender_phone%"
        fax: "%sender_fax%"
        mail: "%sender_mail%"
        web: "%sender_web%"
        mwstId: "%sender_mwstid%"
        bank: "%sender_bank%"
        iban: "%sender_iban%"
        kontoNr: "%sender_kontonr%"
    mwstPercent: 8

sentry:
  dsn: "%sentry_dsn%"
