imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
      dbname: "%database_name%_test"

swiftmailer:
    disable_delivery: true


security:
    firewalls:
         main:
             pattern:           ^/
             form_login:        false
             logout:            true
             anonymous:         true
