DimeTimetrackerFrontendBundle:
    resource: "@DimeTimetrackerFrontendBundle/Resources/config/routing.yml"

DimeTimetrackerBundle:
    type:     rest
    resource: "@DimeTimetrackerBundle/Resources/config/routing.yml"
    prefix:   /api
    defaults: { _format: json }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
