DimeTimetrackerFrontendBundle:
    resource: "@DimeTimetrackerFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

DimeTimetrackerBundle:
    resource: "@DimeTimetrackerBundle/Controller/"
    type:     annotation
    prefix:   /api/

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
