DimeFrontendBundle:
    resource: "@DimeFrontendBundle/Resources/config/routing.yml"
    prefix:   /

DimeOfferBundle:
    type: rest
    resource: "@DimeOfferBundle/Resources/config/routing.yml"
    prefix:   /api

DimeInvoiceBundle:
    type: rest
    resource: "@DimeInvoiceBundle/Resources/config/routing.yml"
    prefix:   /api

DimeTimetrackerBundle:
    type: rest
    prefix: /api
    resource: "@DimeTimetrackerBundle/Resources/config/routing.yml"

DimeReportBundle:
    type: rest
    prefix: /api
    resource: "@DimeReportBundle/Resources/config/routing.yml"

DimeEmployeeBundle:
    type: rest
    prefix: /api
    resource: "@DimeEmployeeBundle/Resources/config/routing.yml"
    
DimeTimetrackerBundleSecurity:
    resource: "@DimeTimetrackerBundle/Resources/config/security_routing.yml"

json_schema:
    resource: "@KnpJsonSchemaBundle/Resources/config/routing.yml"
    prefix: /api/v1

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc