DimeTimetrackerFrontendBundle:
    resource: "@DimeTimetrackerFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

DimeTimetrackerBundle:
    type:     rest
    resource: "@DimeTimetrackerBundle/Resources/config/routing/routing.yml"
    prefix:   /api
    defaults: { _format: json }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
