services:
    dime.employee.form.type:
        class: Dime\EmployeeBundle\Form\Type\EmployeeFormType
        tags: [{ name: form.type }]

    dime.period.form.type:
        class: Dime\EmployeeBundle\Form\Type\PeriodFormType
        tags: [{ name: form.type }]

    dime.holiday.form.type:
        class: Dime\EmployeeBundle\Form\Type\HolidayFormType
        tags: [{ name: form.type }]