parameters:
    generic_handler: Dime\EmployeeBundle\Handler\GenericHandler

services:
    dime.employee.handler:
        class: Dime\TimetrackerBundle\Handler\UserHandler
        arguments: [ "@doctrine.orm.entity_manager", Dime\EmployeeBundle\Entity\Employee, "@service_container", "@fos_user.user_manager", "em", Dime\EmployeeBundle\Form\Type\EmployeeFormType]

    dime.period.handler:
        class: Dime\TimetrackerBundle\Handler\PeriodHandler
        arguments: [ "@doctrine.orm.entity_manager", Dime\EmployeeBundle\Entity\Period,  "@service_container", "p", Dime\EmployeeBundle\Form\Type\PeriodFormType]

    dime.holiday.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", Dime\EmployeeBundle\Entity\Holiday,  "@service_container", "h", Dime\EmployeeBundle\Form\Type\HolidayFormType]

    dime.persist.event.timeslice:
         class: Dime\EmployeeBundle\EventListener\TimeslicePersistSubscriber
         calls:
            - [ setContainer,  ["@service_container"] ]
         tags:
            - { name: kernel.event_subscriber }

    dime.persist.event.period:
         class: Dime\EmployeeBundle\EventListener\PeriodPersistSubscriber
         calls:
            - [ setContainer,  ["@service_container"] ]
         tags:
            - { name: kernel.event_subscriber }
    dime.persist.event.holiday:
         class: Dime\EmployeeBundle\EventListener\HolidayPersistSubscriber
         calls:
            - [ setContainer,  ["@service_container"] ]
         tags:
            - { name: kernel.event_subscriber }