name: DimeClient
version: 0.0.1
author: Till Wegmüller
description: A WebApp Client for DimeErp
homepage: http://github.com/stiftungswo/Dime
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: ">=1.1.1 <2.0.0"
  angular_ui: ">=0.6.8 <0.7.0"
  browser: any
  route_hierarchical: '>=0.5.0 <0.7.0'
  sass: '>=0.4.0 <0.5.0'
  script_inliner: '>=1.0.0 <2.0.0'
  hammock:
    git:
        url: https://github.com/toasterson/hammock.git
        ref: master
  hammock_mapper: 
    git:
        url: https://github.com/stiftungswo/hammock_mapper.git
        ref: master
  crypto: ">=0.9.0 <0.10.0"
transformers:
- script_inliner
- angular
- $dart2js:
    checked: false
    minify: false
    verbose: false
    suppressWarnings: false
    suppressHints: false
    terse: false