#!/bin/sh
dartfiles=$(git diff --cached --name-only --diff-filter=ACM "*.dart" | tr '\n' ' ')
phpfiles=$(git diff --cached --name-only --diff-filter=ACM "*.php" | tr '\n' ' ')


exitstatus=0


if [[ ! ( -z "$dartfiles" ) ]];
then

    git checkout-index --prefix=git-export-dir/ -a
    cd git-export-dir/

    echo "$dartfiles" | xargs dartfmt -n --set-exit-if-changed --line-length 140

    if [[ $? != 0 ]];
    then
        echo
        echo "dart files were not properly formatted, please format them with:"
        echo "dartfmt -w --line-length 140 <path>"
        echo


        exitstatus=1
    fi

    cd ..
fi

if [[ ! ( -z "$phpfiles" ) ]];
then

    [ ! -d git-export-dir/ ] && git checkout-index --prefix=git-export-dir/ -a
    echo "$phpfiles" | xargs docker run --rm  -v $(pwd)/git-export-dir:/app -w /app texthtml/phpcs:3.2.3 phpcs --standard=psr2 | grep "PHPCBF CAN FIX" > /dev/null

    if [[ $? -eq 0 ]];
    then
        echo
        echo "php files were not properly formatted, please format them with:"
        echo "composer run format"
        echo

        exitstatus=1
    fi
fi

[ -d git-export-dir/ ] && rm -rf git-export-dir/

exit $exitstatus
