Dime\TimetrackerBundle\Entity\Service:
    service_1:
        name: consulting
        alias: consulting
        vat: 0.08
        description: This is a detailed description
        chargeable: true
        rates: <randomElements(array(@rate_1))>
        user: @user_1
    serviceHour_{1..20}:
        name: <word()>
        alias: <slug()>
        vat: <randomElement(array (0.025, 0.08))>
        description: <text(255)>
        chargeable: <boolean(90)>
        rates: 2x @rateHour_*
        user: @user_*
    serviceDay_{1..20}:
        name: <word()>
        alias: <slug()>
        vat: <randomElement(array (0.025, 0.08))>
        description: <text(255)>
        chargeable: <boolean(90)>
        rates: 2x @rateDay_*
        user: @user_*
    serviceNone_{1..20}:
        name: <word()>
        alias: <slug()>
        vat: <randomElement(array (0.025, 0.08))>
        description: <text(255)>
        chargeable: <boolean(90)>
        rates: 2x @rateNone_*
        user: @user_*
    servicePauschal_{1..20}:
        name: <word()>
        alias: <slug()>
        vat: <randomElement(array (0.025, 0.08))>
        description: <text(255)>
        chargeable: <boolean(90)>
        rates: 2x @ratePauschal_*
        user: @user_*