<?php

namespace Dime\OfferBundle\Entity;

use Dime\TimetrackerBundle\Entity\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferPositionRepository extends EntityRepository
{
    /**
     * Search for name or alias
     *
     * @param string            $text
     * @param QueryBuilder      $qb
     * @return OfferPositionRepository
     */
    public function search($text, QueryBuilder $qb = null)
    {
        if ($qb == null) {
            $qb = $this->builder;
        }
    
        $aliases = $qb->getRootAliases();
        $alias = array_shift($aliases);
    
        $qb->andWhere($qb->expr()->orX(
            $qb->expr()->like($alias . '.name', ':text_like')
        ));
        $qb->setParameter('text_like', '%' . $text . '%');
    
        return $this;
    }
    
    /**
     *
     * @param                   $date
     * @param QueryBuilder      $qb
     *
     * @return OfferPositionRepository
     */
    public function scopeByDate($date, QueryBuilder $qb = null)
    {
        return $this;
    }

    /**
     * Filter by offer id
     *
     * @param                            $id, integer
     * @param \Doctrine\ORM\QueryBuilder $qb
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function scopeByOffer($id, QueryBuilder $qb = null)
    {
        return $this->scopeByField('offer', $id, $qb);
    }
}
