services:
    dime_invoicebundle_invoicediscountformtype:
        class: Dime\InvoiceBundle\Form\Type\InvoiceDiscountFormType
        tags: [{ name: "form.type", alias: "dime_invoicebundle_invoicediscountformtype" }]

    dime.invoicebundle.invoice.formtype:
        class: Dime\InvoiceBundle\Form\Type\InvoiceFormType
        tags: [{ name: "form.type", alias: "dime_invoicebundle_invoiceformtype" }]

    dime.invoicebundle.invoiceitem.formtype:
            class: Dime\InvoiceBundle\Form\Type\InvoiceItemFormType
            tags: [{ name: "form.type", alias: "dime_invoicebundle_invoiceitemformtype" }]

    dime.invoicebundle.costgroup.formtype:
            class: Dime\InvoiceBundle\Form\Type\CostGroupFormType
            tags: [{ name: "form.type", alias: "dime_invoicebundle_costgroupformtype" }]        
