services:
    dime_invoicebundle_invoicediscountformtype:
        class: Dime\InvoiceBundle\Form\Type\InvoiceDiscountFormType
        tags: [{ name: "form.type" }]

    dime.invoicebundle.invoice.formtype:
        class: Dime\InvoiceBundle\Form\Type\InvoiceFormType
        tags: [{ name: "form.type" }]

    dime.invoicebundle.invoiceitem.formtype:
            class: Dime\InvoiceBundle\Form\Type\InvoiceItemFormType
            tags: [{ name: "form.type" }]

    dime.invoicebundle.costgroup.formtype:
            class: Dime\InvoiceBundle\Form\Type\CostgroupFormType
            tags: [{ name: "form.type" }]

    dime.invoicebundle.invoicecostgroup.formtype:
            class: Dime\InvoiceBundle\Form\Type\InvoiceCostgroupFormType
            tags: [{ name: "form.type" }]
