services:
    dime.offer.form.type:
        class: Dime\OfferBundle\Form\Type\OfferFormType
        tags: [{ name: form.type }]

    dime.offerposition.form.type:
        class: Dime\OfferBundle\Form\Type\OfferPositionFormType
        tags: [{ name: form.type }]

    dime.offerstatusuc.form.type:
        class: Dime\OfferBundle\Form\Type\OfferStatusUCFormType
        tags: [{ name: form.type }]

    dime.offerdiscount.form.type:
        class: Dime\OfferBundle\Form\Type\OfferDiscountFormType
        tags: [{ name: form.type }]