# Configuration for librarian-puppet. For example:
#
forge "https://forge.puppetlabs.com"

mod "puppetlabs/apache", "1.5.0"
mod "puppetlabs/mysql", "3.4.0"
mod "puppetlabs/stdlib", "4.6.0"
mod "puppetlabs/concat", "1.2.3"
mod "herculesteam/augeasproviders", "2.1.3"
mod "stahnma/epel", "1.0.2"
