# Configuration for librarian-puppet. For example:
#
forge "https://forge.puppetlabs.com"

mod "puppetlabs/apache", "1.1.0"
mod "puppetlabs/mysql", "2.2.3"
mod "puppetlabs/stdlib", "4.2.2"
mod "puppetlabs/concat", "1.1.0"
mod "domcleal/augeasproviders", "1.2.0"
mod "stahnma/epel", "0.1.0"
