parameters:

services:
    swo_commons.form_type.address:
            class: Swo\CustomerBundle\Form\Type\AddressFormType
            tags:
                - { name: form.type }

    swo_commons.form_type.phone:
                class: Swo\CustomerBundle\Form\Type\PhoneFormType
                tags:
                    - { name: form.type }