parameters:
  generic_handler: Dime\TimetrackerBundle\Handler\GenericHandler
services:
  swo.company.handler:
    class: Swo\CustomerBundle\Handler\CompanyHandler
    arguments: [ "@doctrine.orm.entity_manager", Swo\CustomerBundle\Entity\Company,  "@service_container", "co", Swo\CustomerBundle\Form\Type\CompanyFormType]
  swo.person.handler:
    class: Swo\CustomerBundle\Handler\PersonHandler
    arguments: [ "@doctrine.orm.entity_manager", Swo\CustomerBundle\Entity\Person,  "@service_container", "pe", Swo\CustomerBundle\Form\Type\PersonFormType]
  swo.phone.handler:
    class: %generic_handler%
    arguments: [ "@doctrine.orm.entity_manager", Swo\CustomerBundle\Entity\Phone,  "@service_container", "ph", Swo\CustomerBundle\Form\Type\PhoneFormType]
  swo.address.handler:
    class: %generic_handler%
    arguments: [ "@doctrine.orm.entity_manager", Swo\CustomerBundle\Entity\Address,  "@service_container", "ad", Swo\CustomerBundle\Form\Type\AddressFormType]
  swo.customer.handler:
    class: %generic_handler%
    arguments: [ "@doctrine.orm.entity_manager", Swo\CustomerBundle\Entity\Customer,  "@service_container", "cu", Swo\CustomerBundle\Form\Type\CustomerFormType]
