parameters:
  generic_handler: Swo\CommonsBundle\Handler\GenericHandler
services:
  swo.company.handler:
    class: Swo\CustomerBundle\Handler\CompanyHandler
    arguments: [ "@doctrine.orm.entity_manager", Swo\CustomerBundle\Entity\Company,  "@service_container", "co", Swo\CustomerBundle\Form\Type\CompanyFormType]

  swo.person.handler:
    class: Swo\CustomerBundle\Handler\PersonHandler
    arguments: [ "@doctrine.orm.entity_manager", Swo\CustomerBundle\Entity\Person,  "@service_container", "pe", Swo\CustomerBundle\Form\Type\PersonFormType]